# Generated by Django 6.0.4 on 2026-04-15 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("escola", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="professor",
            name="email",
        ),
    ]
