# Generated by Django 6.0.4 on 2026-04-11 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Curso",
            fields=[
                (
                    "codigo",
                    models.IntegerField(
                        help_text="Ex: 260", primary_key=True, serialize=False
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("grau", models.CharField(blank=True, max_length=100, null=True)),
                ("descricao", models.TextField(blank=True, null=True)),
                (
                    "logotipo",
                    models.ImageField(blank=True, null=True, upload_to="cursos/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Docente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("biografia", models.TextField(blank=True, null=True)),
                (
                    "fotografia",
                    models.ImageField(blank=True, null=True, upload_to="docentes/"),
                ),
                (
                    "link_ciencia_id",
                    models.URLField(
                        blank=True,
                        help_text="Link para o Ciência ID ou LinkedIn",
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Formacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("instituicao", models.CharField(max_length=200)),
                ("curso_ou_certificado", models.CharField(max_length=200)),
                ("data_inicio", models.DateField()),
                ("data_fim", models.DateField(blank=True, null=True)),
                ("descricao", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Interesse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("descricao", models.TextField(blank=True)),
                (
                    "icone",
                    models.CharField(
                        blank=True, help_text="Ex: fa-gamepad", max_length=50
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MakingOf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("etapa", models.CharField(max_length=100)),
                ("data", models.DateTimeField(auto_now_add=True)),
                ("decisoes", models.TextField()),
                ("erros_solucoes", models.TextField(blank=True)),
                ("imagem_caderno", models.ImageField(upload_to="makingof/")),
                ("uso_ia", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Perfil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "fotografia",
                    models.ImageField(blank=True, null=True, upload_to="perfil/"),
                ),
                ("biografia", models.TextField()),
                ("linkedin", models.URLField(blank=True, null=True)),
                ("github", models.URLField(blank=True, null=True)),
                (
                    "curriculo_pdf",
                    models.FileField(blank=True, null=True, upload_to="curriculos/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Projeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descricao", models.TextField()),
                (
                    "imagem",
                    models.ImageField(blank=True, null=True, upload_to="projetos/"),
                ),
                ("ano", models.IntegerField()),
                ("link_github", models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Tecnologia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("acronimo", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "logotipo",
                    models.ImageField(blank=True, null=True, upload_to="tecnologias/"),
                ),
                ("link_oficial", models.URLField(blank=True)),
                (
                    "categoria",
                    models.CharField(
                        help_text="Ex: Frontend, Backend, Linguagem", max_length=100
                    ),
                ),
                ("nivel_interesse", models.IntegerField(default=1, help_text="1 a 5")),
                ("descricao", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Competencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("nivel", models.IntegerField(help_text="1 a 5")),
                (
                    "projetos",
                    models.ManyToManyField(blank=True, to="portfolio.projeto"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="projeto",
            name="tecnologias",
            field=models.ManyToManyField(
                related_name="projetos", to="portfolio.tecnologia"
            ),
        ),
        migrations.CreateModel(
            name="TFC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=255)),
                ("autores", models.CharField(max_length=255)),
                ("orientadores", models.CharField(max_length=255)),
                ("ano_realizacao", models.IntegerField()),
                ("resumo", models.TextField()),
                ("link_pdf", models.URLField(blank=True, null=True)),
                ("link_imagem", models.URLField(blank=True, null=True)),
                ("rating", models.IntegerField(default=0)),
                (
                    "curso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tfcs",
                        to="portfolio.curso",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UnidadeCurricular",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo_legivel", models.CharField(max_length=50, unique=True)),
                ("nome", models.CharField(max_length=200)),
                ("ano", models.IntegerField()),
                ("semestre", models.IntegerField()),
                ("ects", models.FloatField()),
                ("imagem", models.ImageField(blank=True, null=True, upload_to="ucs/")),
                ("link_lusofona", models.URLField(blank=True)),
                (
                    "curso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ucs",
                        to="portfolio.curso",
                    ),
                ),
                (
                    "docente_responsavel",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ucs",
                        to="portfolio.docente",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="projeto",
            name="uc",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projetos",
                to="portfolio.unidadecurricular",
            ),
        ),
    ]
