# Generated by Django 6.0.4 on 2026-04-11 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Competencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "nivel",
                    models.IntegerField(help_text="Nível de proficiência (ex: 1 a 5)"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Curso",
            fields=[
                (
                    "codigo",
                    models.IntegerField(
                        help_text="Código do curso (ex: 260 para LEI)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                (
                    "grau",
                    models.CharField(
                        blank=True,
                        help_text="Ex: Licenciatura, Mestrado",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("descricao", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Formacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("instituicao", models.CharField(max_length=200)),
                ("curso_ou_certificado", models.CharField(max_length=200)),
                ("data_inicio", models.DateField()),
                (
                    "data_fim",
                    models.DateField(
                        blank=True,
                        help_text="Deixar em branco se ainda a decorrer",
                        null=True,
                    ),
                ),
                ("descricao", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Interesse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("descricao", models.TextField(blank=True, null=True)),
                (
                    "icone",
                    models.CharField(
                        blank=True,
                        help_text="Classe FontAwesome (ex: fa-solid fa-gamepad)",
                        max_length=50,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tecnologia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("acronimo", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "logotipo",
                    models.ImageField(blank=True, null=True, upload_to="tecnologias/"),
                ),
                (
                    "categoria",
                    models.CharField(
                        help_text="Ex: Frontend, Backend, Base de Dados", max_length=100
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TFC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=255)),
                (
                    "autores",
                    models.CharField(
                        help_text="Nomes dos autores separados por vírgula",
                        max_length=255,
                    ),
                ),
                ("ano_realizacao", models.IntegerField()),
                ("resumo", models.TextField()),
                ("link_repositorio", models.URLField(blank=True, null=True)),
                ("link_video", models.URLField(blank=True, null=True)),
                (
                    "curso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tfcs",
                        to="portfolio.curso",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UnidadeCurricular",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo_legivel",
                    models.CharField(
                        help_text="Código legível da UC da API",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("ano", models.IntegerField()),
                ("semestre", models.IntegerField()),
                ("ects", models.FloatField()),
                (
                    "curso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ucs",
                        to="portfolio.curso",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Projeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descricao", models.TextField()),
                (
                    "imagem_destaque",
                    models.ImageField(blank=True, null=True, upload_to="projetos/"),
                ),
                ("ano_realizacao", models.IntegerField()),
                ("link_github", models.URLField(blank=True, null=True)),
                ("link_live", models.URLField(blank=True, null=True)),
                (
                    "tecnologias",
                    models.ManyToManyField(
                        related_name="projetos", to="portfolio.tecnologia"
                    ),
                ),
                (
                    "uc",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projetos",
                        to="portfolio.unidadecurricular",
                    ),
                ),
            ],
        ),
    ]
