# Generated by Django 6.0.4 on 2026-04-11 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MakingOf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("etapa", models.CharField(max_length=100)),
                ("data", models.DateTimeField(auto_now_add=True)),
                ("decisoes", models.TextField()),
                ("erros_solucoes", models.TextField(blank=True)),
                ("imagem_caderno", models.ImageField(upload_to="makingof/")),
                ("uso_ia", models.TextField(blank=True)),
            ],
        ),
        migrations.RenameField(
            model_name="projeto",
            old_name="ano_realizacao",
            new_name="ano",
        ),
        migrations.RenameField(
            model_name="projeto",
            old_name="imagem_destaque",
            new_name="imagem",
        ),
        migrations.RenameField(
            model_name="tfc",
            old_name="link_repositorio",
            new_name="link_imagem",
        ),
        migrations.RenameField(
            model_name="tfc",
            old_name="link_video",
            new_name="link_pdf",
        ),
        migrations.RemoveField(
            model_name="projeto",
            name="link_live",
        ),
        migrations.AddField(
            model_name="competencia",
            name="projetos",
            field=models.ManyToManyField(blank=True, to="portfolio.projeto"),
        ),
        migrations.AddField(
            model_name="curso",
            name="logotipo",
            field=models.ImageField(blank=True, null=True, upload_to="cursos/"),
        ),
        migrations.AddField(
            model_name="tecnologia",
            name="descricao",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="tecnologia",
            name="link_oficial",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="tecnologia",
            name="nivel_interesse",
            field=models.IntegerField(default=1, help_text="1 a 5"),
        ),
        migrations.AddField(
            model_name="tfc",
            name="orientadores",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tfc",
            name="rating",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="unidadecurricular",
            name="docente_responsavel",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="unidadecurricular",
            name="imagem",
            field=models.ImageField(blank=True, null=True, upload_to="ucs/"),
        ),
        migrations.AddField(
            model_name="unidadecurricular",
            name="link_lusofona",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="competencia",
            name="nivel",
            field=models.IntegerField(help_text="1 a 5"),
        ),
        migrations.AlterField(
            model_name="curso",
            name="codigo",
            field=models.IntegerField(
                help_text="Ex: 260", primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="curso",
            name="grau",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="formacao",
            name="data_fim",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="interesse",
            name="descricao",
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="interesse",
            name="icone",
            field=models.CharField(
                blank=True, default=1, help_text="Ex: fa-gamepad", max_length=50
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="projeto",
            name="link_github",
            field=models.URLField(blank=True, default="Não indicado"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="projeto",
            name="uc",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projetos",
                to="portfolio.unidadecurricular",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="tecnologia",
            name="categoria",
            field=models.CharField(
                help_text="Ex: Frontend, Backend, Linguagem", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="autores",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="unidadecurricular",
            name="codigo_legivel",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
